- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: centos.yml
  when: ansible_distribution == "CentOS"
- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"
- include_tasks: alpine.yml
  when: ansible_distribution == "Alpine"
- include_tasks: archlinux.yml
  when: ansible_distribution == "Arch Linux"
