- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
- include_tasks: centos8.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"
- include_tasks: alpine.yml
  when: ansible_distribution == "Alpine"
- import_tasks: common.yml
