- name: apt key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
- name: name
  command: lsb_release -cs
  register: lsbrel
- name: repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsbrel.stdout }} stable
- name: package
  apt:
    update_cache: yes
    name:
     - docker-ce
